In [1]:
import json
import re
from pathlib import Path
from typing import List, Tuple, Optional
import pandas as pd
from tqdm.auto import tqdm
tqdm.pandas()

In [2]:
fs = sorted(Path("../data/json2").glob("*.json"))
print(f"{len(fs)} threads")

10257 threads

In [3]:
from IPython.display import display
# load output from
df3 = pd.read_parquet("../outputs/df_links4.parquet")
df3

,score,n_links,n_comments,comments,thread_urls,first_link_utc,last_link_utc,url
title,,,,,,,,
Worth the Candle,1453,110,110,[{'author_flair_text': 'Self-Appointed Court S...,[https://reddit.com/r/rational/comments/f1rj3l...,2017-07-28 13:17:36,2024-04-17 19:03:01,[https://archiveofourown.org/works/11478249/ch...
"Alexander Wales - The Metropolitan Man, Shadows of the Limelight",1408,22,22,[{'author_flair_text': 'Time flies like an arr...,[https://reddit.com/r/rational/comments/8mqrd0...,2015-04-18 18:13:47,2021-04-29 20:00:04,[https://www.patreon.com/alexanderwales]
A Practical Guide to Evil,1034,94,94,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/dutkzh...,2016-04-05 18:53:21,2024-08-09 10:10:21,"[https://practicalguidetoevil.wordpress.com/, ..."
Worm,925,83,83,[{'author_flair_text': 'Emergency Mustelid Hol...,[https://reddit.com/r/rational/comments/f1rj3l...,2014-01-27 02:09:42,2024-11-22 21:39:11,"[https://parahumans.wordpress.com/, https://pa..."
Mother of Learning,880,93,93,"[{'author_flair_text': 'Utopian Smut Peddler',...",[https://reddit.com/r/rational/comments/dutkzh...,2014-07-26 08:21:12,2024-05-21 07:04:42,[https://www.fictionpress.com/s/2961893/1/Moth...
...,...,...,...,...,...,...,...,...
Heartbreaker,-6,1,1,[{'author_flair_text': 'https://i.imgur.com/OQ...,[https://reddit.com/r/rational/comments/48akta...,2016-02-29 20:57:08,2016-02-29 20:57:08,[https://parahumans.wordpress.com/2012/01/17/b...
picking RPG clothes based on maxing stats instead of whether they match or not,-6,2,2,"[{'author_flair_text': None, 'body': 'It seems...",[https://reddit.com/r/rational/comments/9h1454...,2018-09-19 02:26:27,2018-09-19 04:51:09,[https://youtu.be/xq1tN9jZI80]
Orthogonality thesis,-8,2,2,"[{'author_flair_text': None, 'body': 'I don't ...",[https://reddit.com/r/rational/comments/3vc0si...,2015-12-04 18:17:07,2016-07-11 16:27:30,[https://wiki.lesswrong.com/wiki/Orthogonality...
"When starting school, younger children are more likely to be diagnosed with ADHD",-9,1,1,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/a1t6um...,2018-11-30 17:17:49,2018-11-30 17:17:49,[https://news.harvard.edu/gazette/story/2018/1...
Is There A Replicability Crisis In Psychology? New Study Says: Its Complicated,-9,1,1,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/a1t6um...,2018-11-30 17:17:49,2018-11-30 17:17:49,[https://sciencetrends.com/is-there-a-replicab...

## Extra get a llm summary of each link [WIP]

Grab all md's that mention a story, ask claude to summarize

We could also get total karma per mention

In [4]:
import dotenv
from anycache import anycache

dotenv.load_dotenv()
from openai import OpenAI

client = OpenAI()

import tiktoken

enc = tiktoken.encoding_for_model("gpt-4o-mini")
cost = 0.150 / 1e6

In [5]:
# load all md posts 
md_posts = []
fs = sorted(Path("../data/cache2").glob("*.md"))
for f in fs:
    s = f.open().read()
    md_posts.append(s)


# order by date
def md2date(s: str) -> str:
    return s.split('* Created: ')[1].split('\n')[0]

md_posts = sorted(md_posts, key=md2date)
md2date(md_posts[0]), md2date(md_posts[-1])

('2009-11-25T02:34:03', '2024-12-23T15:00:14')

In [6]:

def get_post_context(urls: List[str], char_budget=100000, min_size=1000) -> str:
    # TODO maybe I should just get comment with links, and children?
    assert len(urls) > 0
    # from comments
    # return df3.loc[title].comments

    # or I could just all markdowns with

    # TODO use langchain chunking?

    matches = []
    for ii, post in enumerate(md_posts):
        for url in urls:
            if url in post:
                matches.append(post)
                break

    budget_pp = char_budget / len(matches)
    budget_pp = max(budget_pp, min_size)
    s = ""
    for i in range(len(matches)):
        post = matches[i]

        for url in urls:
            if url in post:
                ind = post.index(url)

        i0 = int(max(0, ind - budget_pp // 4))
        i1 = int(min(len(post), ind + budget_pp // 4 * 3))
        post_chunk = post[i0:i1]
        if i0 > 0:
            post_chunk = "..." + post_chunk
        if i1 < len(post):
            post_chunk = post_chunk + "..."

        s += f"\n\n----- Thread {ii} -----\n\n" + post_chunk

    # if too large get first N//2 and last N//2
    if len(s) > char_budget:
        s = s[:char_budget // 2] + "..." + s[-char_budget // 2:]
    return s


# url = df3.url[0].split('\n')
# print(url)
# c = get_context(url, 400000)
# print(c[:1000])

In [7]:
df3.iloc[-1].url

array(['https://sciencetrends.com/is-there-a-replicability-crisis-in-psychology-new-study-says-its-complicated/'],
      dtype=object)

In [8]:
# QC test with long and short context
# urls = ['https://archiveofourown.org/works/11478249/chapters/25740126',
#        'https://www.royalroad.com/fiction/25137/worth-the-candle',
#        'http://archiveofourown.org/works/11478249?view_full_work=true',
#        'http://archiveofourown.org/works/11478249/chapters/25740126',
#        'https://archiveofourown.org/works/11478249']
# c = get_post_context(urls, 400000)
# print(urls)
# print(c)

# # urls = ['https://www.amazon.com/Becoming-Batman-Possibility-Paul-Zehr/dp/0801890632']
# # c = get_post_context(urls, 400000)
# # print(urls)
# # print(c)

In [9]:


from pydantic import BaseModel, Field


class FictionInfo(BaseModel):
    title: str
    description: str = Field(description="A few paragraphs of very concise, informative, dense, description of the work")
    tags: List[str] = Field(
        description="""Long list of common descriptors: format (web serial, fanfic, lightnovel, short, complete, comic), genre (scifi, fantasy)
        Key elements (rational, timeloop, litrpg, progression, cultivation, isekai)
        Content notes (grimdark, romance, harem, queer, funny, NSFW)
        """
    )

    # status: Optional[str] = Field(description="complete/ongoing/hiatus/abandoned")
    # type: str = Field(description='e.g. fanfiction, original, comic, etc.')

    reviews_quotes: List[str] = Field(
        description="Directly and fully quote excerpts from every single users' comments about the fiction"
    )
    reviews_summary: Optional[str] = Field(
        description="Structured, dry, and concise summary of reviews"
    )
    reccomendations: Optional[str] = Field(
        description="Why users recommend it"
    )
    disrecommendations: Optional[str] = Field(
        description="Why users disrecommend it"
    )
    why: Optional[str] = Field(
        description="Why/when might readers of r/rational like it"
    )
    if_you_liked_x_you_will_like_this: List[str] = Field(
        description="Fans of X will also like the work. Exhaustively list ALL of X mentioned in the discussions."
    )

    quality: float = Field(
        # ge=0.0, le=10.0,
        description="Overall user sentiment out of 10"
    )
    rationality: Optional[float] = Field(
        # ge=0.0, le=10.0,
        description="Systematic worldbuilding, character competence, logical consistency. Where HPMOR is a 10 and Worm is a 5."
    )
    rating_writing: Optional[float]
    rating_plot: Optional[float]
    rating_character: Optional[float]
    rating_worldbuilding: Optional[float]


f_cache_llm = Path("../outputs/.anycache3")


# @anycache(f_cache_llm)
def get_llm_summary(title: str, urls: str, context: str):
    chat_completion = client.beta.chat.completions.parse(
        messages=[
            {
                "role": "system",
                "content": "You are Gwern Branwern, an internet librarian who specializes in rational fiction. You are summarising community reccomendations from r/rational into a dry, informative, concise, and structured format for your own personal notes. Because it's private you can be consise, frank, and opinionated.",
            },
            {
                "role": "user",
                "content": f"""Using the given structure, summarize the parts of these discussions where they talk about {title} (urls: {urls}).

### Context:

{context}""",
            },
        ],
        model="gpt-4o-mini",
        response_format=FictionInfo,
    )

    return chat_completion.choices[0].message.parsed.__dict__

In [10]:
# import shutil
# shutil.rmtree(f_cache_llm, ignore_errors=True)

In [11]:
from openai.lib._pydantic import to_strict_json_schema

to_strict_json_schema(FictionInfo)

{'properties': {'title': {'title': 'Title', 'type': 'string'},
  'description': {'description': 'A few paragraphs of very concise, informative, dense, description of the work',
   'title': 'Description',
   'type': 'string'},
  'tags': {'description': 'Long list of common descriptors: format (web serial, fanfic, lightnovel, short, complete, comic), genre (scifi, fantasy)\n        Key elements (rational, timeloop, litrpg, progression, cultivation, isekai)\n        Content notes (grimdark, romance, harem, queer, funny, NSFW)\n        ',
   'items': {'type': 'string'},
   'title': 'Tags',
   'type': 'array'},
  'reviews_quotes': {'description': "Directly and fully quote excerpts from every single users' comments about the fiction",
   'items': {'type': 'string'},
   'title': 'Reviews Quotes',
   'type': 'array'},
  'reviews_summary': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
   'description': 'Structured, dry, and concise summary of reviews',
   'title': 'Reviews Summary'},
  'reccomendations': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
   'description': 'Why users recommend it',
   'title': 'Reccomendations'},
  'disrecommendations': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
   'description': 'Why users disrecommend it',
   'title': 'Disrecommendations'},
  'why': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
   'description': 'Why/when might readers of r/rational like it',
   'title': 'Why'},
  'if_you_liked_x_you_will_like_this': {'description': 'Fans of X will also like the work. Exhaustively list ALL of X mentioned in the discussions.',
   'items': {'type': 'string'},
   'title': 'If You Liked X You Will Like This',
   'type': 'array'},
  'quality': {'description': 'Overall user sentiment out of 10',
   'title': 'Quality',
   'type': 'number'},
  'rationality': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
   'description': 'Systematic worldbuilding, character competence, logical consistency. Where HPMOR is a 10 and Worm is a 5.',
   'title': 'Rationality'},
  'rating_writing': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
   'title': 'Rating Writing'},
  'rating_plot': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
   'title': 'Rating Plot'},
  'rating_character': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
   'title': 'Rating Character'},
  'rating_worldbuilding': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
   'title': 'Rating Worldbuilding'}},
 'required': ['title',
  'description',
  'tags',
  'reviews_quotes',
  'reviews_summary',
  'reccomendations',
  'disrecommendations',
  'why',
  'if_you_liked_x_you_will_like_this',
  'quality',
  'rationality',
  'rating_writing',
  'rating_plot',
  'rating_character',
  'rating_worldbuilding'],
 'title': 'FictionInfo',
 'type': 'object',
 'additionalProperties': False}

In [14]:
llm_info = []


l = min(1000, len(df3))
for i in tqdm(range(0, l)):
    title = df3.index[i]
    urls = df3.iloc[i].url

    context = get_post_context(urls, char_budget=50000)
    tokens = len(enc.encode(context))
    print(
        f"Input Tokens: {tokens}. Input Cost: {cost * tokens:.4f} USD, for title={title} with urls={urls}"
    )

    llm_data = get_llm_summary(title, urls, context)

    llm_data["title2"] = title
    llm_data["url"] = urls

    if i==0:
        print(f"Content: {context[:1000]}")
        display(llm_data)

    llm_info.append(llm_data)

  0%|          | 0/1000 [00:00<?, ?it/s]

Input Tokens: 13920. Input Cost: 0.0021 USD, for title=Worth the Candle with urls=['https://archiveofourown.org/works/11478249/chapters/25740126'
 'https://www.royalroad.com/fiction/25137/worth-the-candle'
 'http://archiveofourown.org/works/11478249?view_full_work=true'
 'http://archiveofourown.org/works/11478249/chapters/25740126'
 'https://archiveofourown.org/works/11478249'
 'http://daystareld.com/podcast/rationally-writing-42/'
 'https://www.royalroad.com/fiction/25137/worth-the-candle/chapter/366577/taking-the-fall']
Content:

----- Thread 10262 -----

## [RT][WIP] Worth the Candle, Ch 1

* Author: u/cthulhuraejepsen  *Fruit flies like a banana**
* URL: http://archiveofourown.org/works/11478249/chapters/25740126
* Score: 32

* Created: 2017-07-14T05:23:38

### Post:

[Link to content](http://archiveofourown.org/works/11478249/chapters/25740126)

### Comments:

> **u/cthulhuraejepsen** [+9]  *Fruit flies like a banana* (49 minutes later)
>
> This is a self-insert litRPG portal fantasy, and I would have made it a Groundhog Day loop if I thought I could fit that in.

> **u/LucidityWaver** [+7]  (2 hours later)
>
> > loosely based on my personal experience of falling into a portal to another world and discovering that I had a character sheet attached to my soul. This story uses some custom CSS for the character sheet and definition tags to allow mouseover on various game terms
>
> I can tel...

----- Thread 10262 -----

..., another four chapters, so if you were one of those people who doesn't read serials

{'title': 'Worth the Candle',
 'description': '*Worth the Candle* is a self-insert litRPG portal fantasy written by u/cthulhuraejepsen. The narrative follows Juniper Smith, a teenage boy unexpectedly transported to a fantasy world inspired by the multiple tabletop RPGs he has run. The story incorporates game mechanics into its plot, offering a unique character sheet and interactive gameplay elements that impact character development and world interaction. As Juniper navigates this new reality, he grapples with existential themes, including the nature of agency and personal identity amidst the fantastical chaos.',
 'tags': ['web serial',
  'fantasy',
  'scifi',
  'litRPG',
  'self-insert',
  'portal fantasy',
  'light',
  'humor',
  'grimdark',
  'harem'],
 'reviews_quotes': ['"This is quickly becoming my favorite litrpg. You need to work a little harder to catch up to the wandering inn."',
  '"I\'m reasonably confident that her beauty is abnormal..."',
  '"Hell of a name for a chapter based around existential horror."',
  '"One of the things I love about *Worth the Candle* is that it tends to avoid shortcuts and oversimplifications."',
  '"There are two more chapters in this \'set\'... as always, thanks for reading."'],
 'reviews_summary': 'The story is well-received for its unique integration of RPG mechanics into a fantasy narrative, engaging characters, and intricate worldbuilding. It stands out as a compelling litrpg that balances humor with serious themes.',
 'reccomendations': 'Readers enjoy *Worth the Candle* for its detailed world-building, character depth, and the reflective integration of gaming elements into the storytelling. It is also appreciated for exploring mature themes and character agency.',
 'disrecommendations': 'Some readers note that the extensive length and pacing might deter those unaccustomed to long-form web serials. Additionally, those not interested in litRPG settings may find the mechanics off-putting.',
 'why': 'Fans of litrpgs, portal fantasies, and those interested in game mechanics should find this story appealing due to its character-driven plot and thoughtful exploration of genre tropes.',
 'if_you_liked_x_you_will_like_this': ['Worm',
  'Mother of Learning',
  'The Wandering Inn',
  'A Practical Guide to Evil',
  'Defiance of the Fall',
  "The Existentialist's Guide to the Universe"],
 'quality': 9.0,
 'rationality': 8.5,
 'rating_writing': 8.0,
 'rating_plot': 8.0,
 'rating_character': 9.0,
 'rating_worldbuilding': 9.0,
 'title2': 'Worth the Candle',
 'url': array(['https://archiveofourown.org/works/11478249/chapters/25740126',
        'https://www.royalroad.com/fiction/25137/worth-the-candle',
        'http://archiveofourown.org/works/11478249?view_full_work=true',
        'http://archiveofourown.org/works/11478249/chapters/25740126',
        'https://archiveofourown.org/works/11478249',
        'http://daystareld.com/podcast/rationally-writing-42/',
        'https://www.royalroad.com/fiction/25137/worth-the-candle/chapter/366577/taking-the-fall'],
       dtype=object)}

Input Tokens: 12769. Input Cost: 0.0019 USD, for title=Alexander Wales - The Metropolitan Man, Shadows of the Limelight with urls=['https://www.patreon.com/alexanderwales']
Input Tokens: 13919. Input Cost: 0.0021 USD, for title=A Practical Guide to Evil with urls=['https://practicalguidetoevil.wordpress.com/'
 'https://practicalguidetoevil.wordpress.com/table-of-contents/'
 'https://practicalguidetoevil.wordpress.com/summary/'
 'https://practicalguidetoevil.wordpress.com/2015/03/25/prologue/'
 'https://practicalguidetoevil.wordpress.com'
 'https://practicalguidetoevil.wordpress.com/2017/08/30/interlude-commanders/'
 'https://practicalguidetoevil.wordpress.com/2018/07/02/court-iii/'
 'https://practicalguidetoevil.wordpress.com/2018/06/01/court-ii/'
 'https://practicalguidetoevil.wordpress.com/2018/05/02/court-i/'
 'https://practicalguidetoevil.wordpress.com/2016/03/02/chapter-14-situation/'
 'https://practicalguidetoevil.wordpress.com/2018/03/07/epilogue-3/'
 'https://practicalguidetoevil.wordpress.com/2018/04/25/chapter-6-hedges/'
 'https://practicalguidetoevil.wordpress.com/2017/09/06/chapter-29-scale/#comment-7216'
 'https://practicalguidetoevil.wordpress.com/2017/07/26/chapter-22-govern/'
 'https://practicalguidetoevil.wordpress.com/2015/03/20/summary'
 'https://practicalguidetoevil.wordpress.com/2018/08/27/chapter-48-shadows/#comment-21305'
 'https://practicalguidetoevil.wordpress.com/2018/12/10/chapter-82-thrice-dead/'
 'https://practicalguidetoevil.wordpress.com/2016/11/02/red-skies/'
 'https://practicalguidetoevil.wordpress.com/2020/07/03/charlatan-iv/'
 'https://practicalguidetoevil.wordpress.com/2015/07/08/chapter-15-company/'
 'https://practicalguidetoevil.wordpress.com/2018/09/12/chapter-55-outskirts/'
 'https://practicalguidetoevil.wordpress.com/2018/07/25/chapter-35-stroll/'
 'https://practicalguidetoevil.wordpress.com/2018/10/22/chapter-66-tremors/'
 'https://practicalguidetoevil.wordpress.com/2020/08/04/five-stories/'
 'https://practicalguidetoevil.wordpress.com/2016/11/16/chapter-44-victory/'
 'https://practicalguidetoevil.wordpress.com/2019/04/29/chapter-33-concord/'
 'https://practicalguidetoevil.wordpress.com/2015/08/12/chapter-20-rise/'
 'https://practicalguidetoevil.wordpress.com/2016/09/07/chapter-37-apprentice/'
 'https://practicalguidetoevil.wordpress.com/2020/09/01/malanza/'
 'https://practicalguidetoevil.wordpress.com/2018/02/23/chapter-68-coda/'
 'https://practicalguidetoevil.wordpress.com/2015/10/07/chapter-28-win-condition/'
 'https://practicalguidetoevil.wordpress.com/2016/04/06/chapter-19-flame/'
 'https://practicalguidetoevil.wordpress.com/2017/10/16/chapter-35-questions/'
 'https://practicalguidetoevil.wordpress.com/2017/09/18/chapter-32-close/'
 'https://practicalguidetoevil.wordpress.com/2017/02/08/reign/'
 'https://practicalguidetoevil.wordpress.com/2016/03/23/chapter-17-aplomb/'
 'https://practicalguidetoevil.wordpress.com/2018/08/29/chapter-49-wrangle/'
 'https://practicalguidetoevil.wordpress.com/2018/05/18/chapter-15-bravura/'
 'https://practicalguidetoevil.wordpress.com/2018/06/08/chapter-18-cradle/'
 'https://practicalguidetoevil.wordpress.com/extra-chapters/'
 'https://practicalguidetoevil.wordpress.com/2018/01/03/chapter-56-recess/'
 'https://practicalguidetoevil.wordpress.com/2017/01/04/epilogue-2/#comment-3569'
 'https://practicalguidetoevil.wordpress.com/2017/08/02/interlude-apprentice/'
 'https://practicalguidetoevil.wordpress.com/2018/05/07/chapter-10-allegro/'
 'https://practicalguidetoevil.wordpress.com/2017/07/17/chapter-19-order-redux/'
 'https://practicalguidetoevil.wordpress.com/2015/03/20/summary/'
 'https://practicalguidetoevil.wordpress.com/maps/']
Input Tokens: 13474. Input Cost: 0.0020 USD, for title=Worm with urls=['https://parahumans.wordpress.com/'
 'https://parahumans.wordpress.com/table-of-contents/'
 'https://parahumans.wordpress.com/category/stories-arcs-1-10/arc-1-gestation/1-01/'
 'https://parahumans.wordpress.com'
 'https://parahumans.wordpress.com/2011/06/11/1-1/'
 'http://parahumans.wordpress.com/table-of-contents/'
 'http://parahumans.wordpress.com/2011/06/11/1-1/'
 'http://parahumans.wordpress.com/' 'http://audioworm.rein-online.org'
 'http://parahumans.wordpress.com/about/']
Input Tokens: 13865. Input Cost: 0.0021 USD, for title=Mother of Learning with urls=['https://www.fictionpress.com/s/2961893/1/Mother-of-Learning'
 'https://www.royalroad.com/fiction/21220/mother-of-learning'
 'https://www.royalroad.com/fictions/best-rated'
 'https://www.fictionpress.com/s/2961893'
 'https://www.royalroad.com/fiction/21220/mother-of-learning/chapter/301778/1-good-morning-brother'
 'https://www.royalroad.com/fiction/21220/mother-of-learning/chapter/307245/26-soulkill'
 'https://www.fictionpress.com/s/2961893/102/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/93/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/49/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/75/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/74/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/106/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/105/Mother-of-Learning'
 'https://www.fictionpress.com/s/2961893/104/Mother-of-Learning']
Input Tokens: 13862. Input Cost: 0.0021 USD, for title=The Metropolitan Man with urls=['https://www.fanfiction.net/s/10360716/1/The-Metropolitan-Man'
 'https://archiveofourown.org/works/17356310/chapters/40838042'
 'https://alexanderwales.com/the-metropolitan-man-1/'
 'https://archiveofourown.org/works/17356310/']
Input Tokens: 13534. Input Cost: 0.0020 USD, for title=Time Braid with urls=['https://www.fanfiction.net/s/5193644/1/Time-Braid'
 'https://www.fanfiction.net/s/5193644'
 'https://www.fanfiction.net/s/5193644/1/Time_Braid'
 'https://www.fanfiction.net/s/5193644/4/Time-Braid'
 'https://m.fanfiction.net/s/5193644/1/'
 'https://m.fanfiction.net/s/5193644/1/Time-Braid'
 'https://www.fanfiction.net/s/5193644/1']
Input Tokens: 14131. Input Cost: 0.0021 USD, for title=Unsong with urls=['http://unsongbook.com/' 'http://unsongbook.com/prologue-2/'
 'https://unsongbook.com/'
 'http://unsongbook.com/interlude-%D7%95-theres-a-hole-in-my-bucket/'
 'http://unsongbook.com/chapter-23-now-descendeth-out-of-heaven-a-city/'
 'http://unsongbook.com/chapter-17-that-the-children-of-jerusalem-may-be-saved-from-slavery/'
 'http://unsongbook.com/chapter-71-but-for-another-gives-its-ease/'
 'http://unsongbook.com/chapter-5-never-seek-to-tell-thy-love/#comment-702'
 'http://unsongbook.com/chapter-20-when-the-stars-threw-down-their-spears/'
 'http://unsongbook.com/chapter-22-whose-ears-have-heard-the-holy-word/#comment-6084'
 'http://unsongbook.com/chapter-4-tools-were-made-and-born-were-hands/#comment-571'
 'http://unsongbook.com/chapter-6-till-we-have-built-jerusalem/'
 'http://unsongbook.com/interlude-%D7%94-the-right-hand-of-god/#comment-2207'
 'http://unsongbook.com/interlude-ח-war-and-peace/'
 'http://unsongbook.com/chapter-30-over-the-dark-deserts/'
 'http://unsongbook.com/chapter-2-arise-to-spiritual-strife/'
 'http://unsongbook.com/chapter-21-thou-also-dwellest-in-eternity/'
 'https://www.audible.com/pd/UNSONG-Audiobook-Version-Podcast/B08JJPNB2N'
 'http://unsongbook.com/chapter-8-laughing-to-scorn-thy-laws-and-terrors/'
 'http://unsongbook.com/chapter-53-lover-of-wild-rebellion/'
 'http://unsongbook.com/chapter-35-the-voices-of-children-in-his-tents/'
 'http://unsongbook.com/chapter-1-dark-satanic-mills/'
 'http://unsongbook.com/chapter-49-terrors-of-the-sun-and-moon/'
 'http://unsongbook.com/chapter-13-the-image-of-eternal-death/'
 'http://unsongbook.com/chapter-44-a-world-within-opening-its-gates/'
 'http://unsongbook.com/book-2-exodus/'
 'http://unsongbook.com/chapter-16-if-perchance-with-iron-power-he-might-avert-his-own-despair/'
 'http://unsongbook.com/chapter-26-for-not-one-sparrow-can-suffer-and-the-whole-universe-not-suffer-also/'
 'http://unsongbook.com/chapter-32-the-human-form-divine/'
 'http://unsongbook.com/chapter-34-why-wilt-thou-rend-thyself-apart-jerusalem/'
 'http://unsongbook.com/chapter-36-my-fathers-business/'
 'http://unsongbook.com/interlude-%D7%96-man-on-the-sphere/'
 'http://unsongbook.com/interlude-%d7%90-the-cracks-in-the-sky/'
 'http://unsongbook.com/chapter-52-the-king-of-light-beheld-her-mourning/'
 'http://unsongbook.com/epilogue/'
 'http://unsongbook.com/chapter-9-with-art-celestial/'
 'http://unsongbook.com/chapter-70-nor-for-itself-hath-any-care/'
 'https://unsongbook.com/chapter-63-my-wrath-burns-to-the-top-of-heaven/']
Input Tokens: 12816. Input Cost: 0.0019 USD, for title=With This Ring with urls=['https://forums.sufficientvelocity.com/threads/with-this-ring-young-justice-si-story-only.25076/'
 'https://forum.questionablequesting.com/threads/with-this-ring-young-justice-si-thread-fourteen.8938/'
 'https://forums.sufficientvelocity.com/threads/with-this-ring-young-justice-si-thread-twelve.25032/'
 'https://forums.spacebattles.com/threads/with-this-ring-young-justice-si-story-only.272850/'
 'http://forums.spacebattles.com/threads/with-this-ring-young-justice-si-story-only.272850/'
 'https://questionablequesting.com/threads/with-this-ring-young-justice-si-thread-fourteen.8938/page-1976#post-6372141'
 'https://forum.questionablequesting.com/threads/with-this-ring-young-justice-si-story-only.8961/'
 'https://forums.spacebattles.com/threads/with-this-ring-young-justice-si.267344/'
 'https://forums.sufficientvelocity.com/threads/with-this-ring-young-justice-si-thread-thirteen.49418/']
Input Tokens: 13504. Input Cost: 0.0020 USD, for title=Twig with urls=['https://twigserial.wordpress.com/'
 'https://twigserial.wordpress.com/about/'
 'https://twigserial.wordpress.com/2014/12/24/taking-root-1-1/'
 'http://audiotwig.dauber.kim/' 'https://twigserial.wordpress.com'
 'https://twigserial.wordpress.com/about' 'https://audiotwig.dauber.kim/'
 'https://www.twigserial.wordpress.com/'
 'https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-04/']
Input Tokens: 13334. Input Cost: 0.0020 USD, for title=Pact with urls=['https://pactwebserial.wordpress.com/'
 'https://pactwebserial.wordpress.com/2013/12/17/bonds-1-1/'
 'http://pactwebserial.wordpress.com/table-of-contents/'
 'https://pactwebserial.wordpress.com'
 'http://pactwebserial.wordpress.com/'
 'https://pactwebserial.wordpress.com/2014/07/05/histories-arc-7/'
 'https://pactwebserial.wordpress.com/table-of-contents/'
 'http://pactwebserial.wordpress.com/2013/12/17/bonds-1-1/'
 'https://www.podcastrepublic.net/podcast/1448857756'
 'https://www.pactwebserial.wordpress.com/']
Input Tokens: 13770. Input Cost: 0.0021 USD, for title=Cordyceps with urls=['https://archiveofourown.org/works/6178036/chapters/14154868'
 'http://archiveofourown.org/works/6178036/chapters/14154868'
 'http://archiveofourown.org/works/6178036'
 'https://archiveofourown.org/works/6178036'
 'http://rationalreads.com/#/works/229']
Input Tokens: 12803. Input Cost: 0.0019 USD, for title=Only Villains Do That with urls=['https://www.royalroad.com/fiction/40182/only-villains-do-that'
 'https://www.royalroad.com/fiction/40182/only-villains-do-that-stubbed-22324']
Input Tokens: 13873. Input Cost: 0.0021 USD, for title=Seventh Horcrux with urls=['https://www.fanfiction.net/s/10677106/1/Seventh-Horcrux'
 'https://m.fanfiction.net/s/10677106/1/Seventh-Horcrux'
 'http://forums.spacebattles.com/threads/seventh-horcrux-thread-2-a-harry-situation.311264/'
 'https://www.fanfiction.net/s/10677106/3/'
 'https://www.fanfiction.net/s/10677106'
 'https://www.dropbox.com/s/71nir8x2p7wd03p/Seventh%20Horcrux.epub?dl=0'
 'https://www.fanfiction.net/s/10677106/'
 'https://archiveofourown.org/works/28926447/chapters/70972632']
Input Tokens: 13218. Input Cost: 0.0020 USD, for title=A Young Woman's Political Record with urls=['https://forums.spacebattles.com/threads/a-young-womans-political-record-youjo-senki-saga-of-tanya-the-evil.660569/'
 'https://forums.spacebattles.com/threads/a-young-womans-political-record-youjo-senki-saga-of-tanya-the-evil.660569/reader/'
 'https://forums.spacebattles.com/threads/a-young-womans-political-record-youjo-senki-saga-of-tanya-the-evil.660569/reader/page-5'
 'https://forums.spacebattles.com/threads/a-young-womans-political-record-youjo-senki-saga-of-tanya-the-evil.660569/page-1151#post-66992473'
 'https://www.fanfiction.net/s/13002064/1/A-Young-Woman-s-Political-Record'
 'https://www.fanfiction.net/s/13002064/1/A-Young-Woman-s-Political-Record/']
Input Tokens: 12562. Input Cost: 0.0019 USD, for title=Ar'Kendrithyst with urls=['https://www.royalroad.com/fiction/26727/arkendrithyst'
 'https://www.royalroad.com/fiction/26727/arkendrithyst/chapter/395143/001']
Input Tokens: 13881. Input Cost: 0.0021 USD, for title=The Waves Arisen with urls=['https://wertifloke.wordpress.com/2015/01/25/chapter-1/'
 'https://wertifloke.wordpress.com/about/'
 'https://wertifloke.wordpress.com/table-of-contents/']
Input Tokens: 12680. Input Cost: 0.0019 USD, for title=Vigor Mortis with urls=['https://www.royalroad.com/fiction/40373/vigor-mortis'
 'https://www.royalroad.com/fiction/40373/vigor-mortis/'
 'https://fiction.live/stories/Vigor-Mortis/MNAj8qQMB8b9asLLn']
Input Tokens: 14316. Input Cost: 0.0021 USD, for title=Harry Potter and the Natural 20 with urls=['https://www.fanfiction.net/s/8096183/1/Harry-Potter-and-the-Natural-20'
 'https://m.fanfiction.net/s/8096183/1/Harry-Potter-and-the-Natural-20'
 'https://www.fanfiction.net/s/8096183'
 'https://fanfiction.net/s/8096183/1/Harry-Potter-and-the-Natural-20']
Input Tokens: 13146. Input Cost: 0.0020 USD, for title=Sanitize with urls=['https://www.fanfiction.net/s/12431866/1/Sanitize'
 'https://archiveofourown.org/works/20721824/chapters/49228244'
 'https://archiveofourown.org/works/20721824/'
 'https://m.fanfiction.net/s/12431866/1/Sanitize'
 'https://m.fanfiction.net/s/12431866/1/Sanitize#google_vignette']
Input Tokens: 14306. Input Cost: 0.0021 USD, for title=Delve with urls=['https://www.royalroad.com/fiction/25225/delve'
 'https://www.royalroad.com/fiction/25225/delve/chapter/368012/001-woodland'
 'https://www.royalroad.com/fiction/25225/delve/']
Input Tokens: 14132. Input Cost: 0.0021 USD, for title=Luminosity with urls=['http://luminous.elcenia.com/' 'https://luminous.elcenia.com/'
 'http://luminous.elcenia.com/story.shtml'
 'http://luminous.elcenia.com/about.shtml'
 'https://luminous.elcenia.com/all.shtml'
 'https://luminous.elcenia.com/story.shtml'
 'http://luminous.elcenia.com/index.shtml'
 'https://www.lesswrong.com/tag/luminosity-fanfiction'
 'http://luminous.elcenia.com']
Input Tokens: 13634. Input Cost: 0.0020 USD, for title=The Erogamer with urls=['https://forum.questionablequesting.com/threads/the-erogamer-original.5465/'
 'https://forum.questionablequesting.com/threads/the-erogamer-original.5465/reader'
 'https://forum.questionablequesting.com/threads/the-erogamer-original-complete.5465/'
 'https://forum.questionablequesting.com/threads/the-erogamer-original-complete.5465/reader'
 'https://forum.questionablequesting.com/threads/5465'
 'https://www.goodreads.com/book/show/36676220-the-erogamer']
Input Tokens: 14327. Input Cost: 0.0021 USD, for title=Harry Potter and the Methods of Rationality with urls=['http://www.hpmor.com/' 'http://hpmor.com/' 'http://www.hpmor.com'
 'https://www.hpmor.com/' 'http://hpmor.com/notes/'
 'http://www.hpmorpodcast.com/?page_id=56']
Input Tokens: 13481. Input Cost: 0.0020 USD, for title=Friendship is Optimal with urls=['https://www.fimfiction.net/story/62074/friendship-is-optimal'
 'https://www.fimfiction.net/story/62074/Friendship-is-Optimal'
 'http://www.fimfiction.net/story/62074/friendship-is-optimal'
 'https://www.fimfiction.net/story/62074/']
Input Tokens: 14118. Input Cost: 0.0021 USD, for title=Marked for Death with urls=['https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/'
 'https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest-story-only.24793/'
 'https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/#post-4925222'
 'https://forums.sufficientvelocity.com/threads/24793'
 'https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/page-6901#post-16076158'
 'https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/page-6408#post-13284746'
 'https://forums.sufficientvelocity.com/threads/marked-for-death-a-rational-naruto-quest.24481/reader']
Input Tokens: 14040. Input Cost: 0.0021 USD, for title=Pokemon: The Origin of Species with urls=['https://www.fanfiction.net/s/9794740/1/Pokemon-The-Origin-of-Species'
 'http://daystareld.com/pokemon/'
 'https://www.fanfiction.net/s/9794740/61/Pokemon-The-Origin-of-Species']
Input Tokens: 12706. Input Cost: 0.0019 USD, for title=Pale with urls=['https://palewebserial.wordpress.com/about/'
 'https://palewebserial.wordpress.com/'
 'https://palewebserial.wordpress.com/2020/05/05/blood-run-cold-0-0/'
 'https://palewebserial.wordpress.com'
 'https://anchor.fm/paleaudiobook/episodes/Pale-0-0-Blood-Runs-Cold-edv2li'
 'https://palewebserial.wordpress.com/table-of-contents/'
 'https://anchor.fm/paleaudiobook']
Input Tokens: 13491. Input Cost: 0.0020 USD, for title=Purple Days with urls=['https://forums.spacebattles.com/threads/purple-days-asoiaf-joffrey-timeloop-au.450894/'
 'https://forums.spacebattles.com/threads/purple-days-asoiaf-joffrey-timeloop-au.450894/reader/'
 'https://forums.spacebattles.com/threads/purple-days-asoiaf-joffrey-timeloop-au.450894/#post-27571185'
 'https://forums.spacebattles.com/threads/purple-days-asoiaf-joffrey-timeloop-au.450894/reader']
Input Tokens: 14902. Input Cost: 0.0022 USD, for title=A Hero's War with urls=['https://www.fictionpress.com/s/3238329/1/A-Hero-s-War'
 'https://www.royalroad.com/fiction/2826/a-heros-war'
 'https://www.fictionpress.com/s/3238329'
 'https://www.fictionpress.com/s/3238329/1'
 'https://www.fictionpress.com/s/3238329/82/A-Hero-s-War']
Input Tokens: 10961. Input Cost: 0.0016 USD, for title=Alexander Wales Wiki | Fandom with urls=['https://worththecandle.wikia.com/wiki/Worth_the_Candle_Wiki'
 'https://worththecandle.fandom.com/wiki/Worth_the_Candle_Wiki'
 'https://worththecandle.wikia.com'
 'http://worththecandle.wikia.com/wiki/Worth_the_Candle_Wiki'
 'https://worththecandle.fandom.com']
Input Tokens: 12684. Input Cost: 0.0019 USD, for title=Lord of the Mysteries with urls=['https://www.wuxiaworld.co/Lord-of-the-Mysteries/1486806.html'
 'https://www.webnovel.com/book/11022733006234505/Lord-of-the-Mysteries'
 'https://www.webnovel.com/book/lord-of-the-mysteries_11022733006234505'
 'https://www.lightnovelworld.co/novel/lord-of-the-mysteries-wn-16091313/chapters'
 'https://novelfull.com/lord-of-the-mysteries.html?page=29&per-page=50'
 'https://www.novelupdates.com/series/lord-of-the-mysteries/ "Lord of the Mysteries"'
 'http://novelfull.com/lord-of-the-mysteries.html'
 'https://boxnovel.com/novel/lord-of-the-mysteries/'
 'https://www.novelupdates.com/series/lord-of-the-mysteries/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-484/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-66'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-290/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-125/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-195'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-470/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-1'
 'https://m.wuxiaworld.co/Lord-of-the-Mysteries/1486806.html'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-397/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-544/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-399/'
 'https://boxnovel.com/novel/lord-of-the-mysteries/chapter-21']

In [13]:
df_llm = pd.DataFrame(llm_info)
df_llm
# also join with df4

# then display as table

,title,description,tags,reviews_quotes,reviews_summary,reccomendations,disrecommendations,why,if_you_liked_x_you_will_like_this,quality,rationality,rating_writing,rating_plot,rating_character,rating_worldbuilding,title2,url
0,Worth the Candle,Worth the Candle is a self-insert litrpg porta...,"[web serial, litrpg, fantasy, self-insert, pro...","[""If you haven't read this, it's a self-insert...",Readers praise the narrative for its unique bl...,The community highly recommends this work for ...,Some users caution that readers not typically ...,Fans of rational fiction and those who enjoy t...,"[Worm, Mother of Learning, The Wandering Inn, ...",9.0,8.0,8.0,9.0,8.0,9.0,Worth the Candle,[https://archiveofourown.org/works/11478249/ch...
1,"The Metropolitan Man, Shadows of the Limelight","""The Metropolitan Man"" and ""Shadows of the Lim...","[web serial, fantasy, rational, superhero, com...","[""Feels a lot like a Sanderson book"", ""Effecti...",The sentiment towards Alexander Wales' works i...,Readers appreciate the complexity of the magic...,Some fans note the infrequency of updates and ...,"Fans of intricate magic systems, moral complex...","[Mistborn, Worm, The Mother of Learning, Worth...",9.0,8.0,8.0,9.0,9.0,8.0,"Alexander Wales - The Metropolitan Man, Shadow...",[https://www.patreon.com/alexanderwales]
2,A Practical Guide to Evil,A Practical Guide to Evil is a web serial that...,"[web serial, fantasy, rational, metanarrative,...","[""Probably one of the better written ones out ...",Readers appreciate the depth of character deve...,"The story's intricate plotting, compelling cha...",Some readers find the prose stylistically awkw...,Fans of rational fiction who enjoy complex cha...,"[Worm, HPMOR, Mother of Learning, Unsong, The ...",9.0,8.0,7.0,9.0,9.0,8.0,A Practical Guide to Evil,"[https://practicalguidetoevil.wordpress.com/, ..."
3,Worm,Worm is a web serial written by John C. 'Wildb...,"[web serial, scifi, superhero, dark, gritty, r...",[I wouldn't really describe Worm as a rational...,"Readers find Worm a compelling, albeit dark de...",Readers recommend Worm for its in-depth charac...,Some users caution that it can be emotionally ...,Fans of rationality-themed works may appreciat...,"[Harry Potter and the Methods of Rationality, ...",9.0,6.0,8.0,9.0,9.0,7.0,Worm,"[https://parahumans.wordpress.com/, https://pa..."